image: maven:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - mvn test

build:
  stage: build
  script:
    - mvn install -DskipTests=true
  artifacts:
    expire_in: 2h
    paths:
      - target/*.jar
  only:
    - master
    - test-ci

deploy:
  when: manual
  stage: deploy
  script:
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 0700 ~/.ssh
    ## Add Known Hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 0644 ~/.ssh/known_hosts
    ## login
    - scp target/bookly*.jar bookly-ci@bookly.online:/root/bookly.jar
    - ssh bookly-ci@bookly.online '/usr/bin/sudo /bin/systemctl restart bookly'
  only:
    - master
    - test-ci