image: java:8-jdk

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

test:
  stage: test
  script:
    - ./mvnw verify

build-prod:
  when: manual
  stage: build
  script:
    - ./mvnw install -DskipTests -P prod
  artifacts:
    expire_in: 2h
    paths:
      - backend/prod/target/*.jar

build-dev:
  stage: build
  script:
    - ./mvnw install -DskipTests -P dev
  artifacts:
    expire_in: 2h
    paths:
      - backend/dev/target/*.jar

deploy-prod:
  when: manual
  stage: deploy
  script:
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 0700 ~/.ssh
    ## Add Known Hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 0644 ~/.ssh/known_hosts
    ## login
    - scp backend/prod/target/backend*.jar bookly-ci@bookly.online:stage/bookly.jar
    - ssh bookly-ci@bookly.online '/usr/bin/sudo /bin/systemctl restart bookly-stage'
  only:
    - master
    - test-ci

deploy-dev:
  when: manual
  stage: deploy
  script:
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 0700 ~/.ssh
    ## Add Known Hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 0644 ~/.ssh/known_hosts
    ## login
    - scp backend/dev/target/backend*.jar bookly-ci@bookly.online:dev/bookly.jar
    - ssh bookly-ci@bookly.online '/usr/bin/sudo /bin/systemctl restart bookly-dev'
