version: '2.2'
services:
  bookly:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backendbookly
    ports:
      - "8080:8080"
      - "8081:8080"
    networks:
      - network1

networks:
  network1: